### PR TITLE
Submitting assignments 1 & 2

### PR DESCRIPTION
**Pull request by davidvaz77**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
Submitting assignments 1 & 2 

## What did you learn from the changes you have made?
The assignments are reflective of all that we have studied in the Production module. 
Notably, working with dask dataframes, creating piplelines & transforming data. 

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
N/A 

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
At one point my code had gotten too complex. I needed the support of one of the Learning Advisors to help me navigate the challenge. 
I was able to get around it by implementing a simpler solution. 

I also mistakenly submitted most of my changes into the main branch because I didn't set up an assignment branch. This is the first module where I have taken this long to submit an assignment. I found the first assignment harder than the second one. 

## How were these changes tested?
I tested the changes with additional code. 

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by davidvaz77** [comment]
Added Assignment 3 along with the pickle file.

**Review by vishnouvina — COMMENTED** [review]
A3 approved

**Comment by ananyajha2000** [comment]
A1 complete

**Comment by ananyajha2000** [comment]
A2 complete

**Pull request closed without merging**
